places_to_visit = ["Japan", "Italy", "New Zealand", "Norway", 
                   "Greece", "Iceland", "Switzerland", "South Africa"]
print("Original list:")
print(places_to_visit)
print("\nAlphabetical order:")
print(sorted(places_to_visit))
print("\nOriginal list again:")
print(places_to_visit)
print("\nReverse alphabetical order:")
print(sorted(places_to_visit, reverse=True))
print("\nOriginal list again:")
print(places_to_visit)
places_to_visit.reverse()
print("\nReversed list:")
print(places_to_visit)
places_to_visit.reverse()
print("\nOriginal list again:")
print(places_to_visit)
places_to_visit.sort()
print("\nPermanently sorted list:")
print(places_to_visit)
places_to_visit.sort(reverse=True)
print("\nPermanently reverse sorted list:")
print(places_to_visit)